[build][build]# Netlify Build Configuration

  command = "npm run build"

  publish = "dist"  command = "npm run build"[build]



[build.environment]  publish = "dist"  command = "npm run build"

  NODE_VERSION = "18.14.1"

  publish = "dist"

[[redirects]]

  from = "/*"[build.environment]

  to = "/index.html"

  status = 200  NODE_VERSION = "18.14.1"[build.environment]

  NODE_VERSION = "18.14.1"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200